### ISSUE TITLE
Simplify power of 2 function.

### ISSUE THREAD

**Issue by JeffProgrammer** [joshmcintyre/proofofworker#1]
Josh,

https://github.com/joshmcintyre/proofofworker/blob/b70ffb1101e9fa08d33c408b0c2cccd4e1602b3a/src/server/crypto.c#L108

That can be simplified to a left shift:

```cpp
int two_power(const int exponent)
{
   if (exponent < 0 || exponent > 31)
      return -1;
   return 1 << exponent;
}
```

Checked to see if the current code would inline to a left shift in GCC, it does not.

**Comment by joshmcintyre** [comment]
Jeff, great catch.

Sorry it took me so long to fix, I got waaaayyyyy sidetracked...thanks for the suggestion!
